name: generators
version: 1.1.0

publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.0
  source_gen: ^1.3.1
  zikzak_inappwebview_internal_annotations:
    path: ../../zikzak_inappwebview_internal_annotations

dev_dependencies:
  build_runner: ^2.4.0
  build_test: ^2.1.7
  test: ^1.24.2
